version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rocky
permissions:
  - object: /var/www/rocky
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type: 
      - directory
  - object: /var/www/rocky
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type: 
      - file
hooks:
  BeforeInstall:
    - location: script/aws/backup_previous_revision.sh
      timeout: 600
      runas: ec2-user
  AfterInstall:
    - location: script/aws/rails_setup.sh
      timeout: 600
      runas: ec2-user